export const columnMapping = {
  'GOLS': 'Gols',
  'ASSISTÊNCIAS': 'Assistências',
  'CHANCES DE GOL': 'Chances de gol',
  'CHANCES COM SUCESSO': 'Chances com sucesso',
  'CHANCES C/ SUCESSO, %': 'Chances c/ sucesso, %',
  'CHANCES CRIADAS': 'Chances criadas',
  'CHUTES': 'Chutes',
  'CHUTES/GOL': 'Chutes/gol',
  'XG': 'xG',
  'CHUTES NO GOL, %': 'Chutes no gol, %',
  'CHUTES/FORA': 'Chutes/fora',
  'HEADER': 'Header',
  'TIROS / POSTE': 'Tiros / poste',
  'ENTRADAS NO TERÇO FINAL': 'Entradas no terço final',
  'ENTRADAS NO TERÇO FINAL ATRAVÉS DE PASSES': 'Entradas no terço final através de passes',
  'ENTRADAS NO TERÇO FINAL ATRAVÉS DE PASSE, % DO TOTAL': 'Entradas no terço final através de passe, % do total',
  'ENTRADAS NO TERÇO FINAL CARREGANDO A BOLA': 'Entradas no terço final carregando a bola',
  'ENTRADAS NO TERÇO FINAL CARREGANDO A BOLA, % DO TOTAL': 'Entradas no terço final carregando a bola, % do total',
  'XA': 'xA',
  'DUELOS DEFENSIVOS': 'Duelos defensivos',
  'DUELOS DEFENSIVOS GANHOS': 'Duelos defensivos ganhos',
  'DUELOS DEFENSIVOS GANHOS, %': 'Duelos defensivos ganhos, %',
  'DUELOS AÉREOS': 'Duelos aéreos',
  'DUELOS AÉREOS GANHOS': 'Duelos aéreos ganhos',
  'DUELOS AÉREOS GANHOS, %': 'Duelos aéreos ganhos, %',
  'DESARMES': 'Desarmes',
  'DESARMES COM SUCESSO': 'Desarmes com sucesso',
  'DESARMES BEM SUCEDIDOS, %': 'Desarmes bem sucedidos, %',
  'INTERCEPTAÇÕES': 'Interceptações',
  'BLOQUEIOS': 'Bloqueios',
  'CORTES': 'Cortes',
  'RECUPERAÇÕES DE BOLA': 'Recuperações de bola',
  'RECUPERAÇÕES DE BOLA NO CAMPO ADVERSÁRIO': 'Recuperações de bola no campo adversário',
  'FALTAS COMETIDAS': 'Faltas cometidas',
  'CARTÕES AMARELOS': 'Cartões amarelos',
  'CARTÕES VERMELHOS': 'Cartões vermelhos',
  'PASSES': 'Passes',
  'PASSES CERTOS': 'Passes certos',
  'PASSES CERTOS, %': 'Passes certos, %',
  'PASSES LONGOS': 'Passes longos',
  'PASSES LONGOS CERTOS': 'Passes longos certos',
  'PASSES LONGOS CERTOS, %': 'Passes longos certos, %',
  'PASSES PARA O TERÇO FINAL': 'Passes para o terço final',
  'PASSES PARA O TERÇO FINAL CERTOS': 'Passes para o terço final certos',
  'PASSES PARA O TERÇO FINAL CERTOS, %': 'Passes para o terço final certos, %',
  'PASSES PARA A ÁREA': 'Passes para a área',
  'PASSES PARA A ÁREA CERTOS': 'Passes para a área certos',
  'PASSES PARA A ÁREA CERTOS, %': 'Passes para a área certos, %',
  'PASSES PROGRESSIVOS': 'Passes progressivos',
  'PASSES PROGRESSIVOS CERTOS': 'Passes progressivos certos',
  'PASSES PROGRESSIVOS CERTOS, %': 'Passes progressivos certos, %',
  'CRUZAMENTOS': 'Cruzamentos',
  'CRUZAMENTOS CERTOS': 'Cruzamentos certos',
  'CRUZAMENTOS CERTOS, %': 'Cruzamentos certos, %',
  'TOQUES NA BOLA': 'Toques na bola',
  'DRIBLE': 'Drible',
  'DRIBLE COM SUCESSO': 'Drible com sucesso',
  'DRIBLE COM SUCESSO, %': 'Drible com sucesso, %',
  'PERDAS DE BOLA': 'Perdas de bola',
  'PERDAS DE BOLA NO PRÓPRIO CAMPO': 'Perdas de bola no próprio campo',
  'CORRIDAS PROGRESSIVAS': 'Corridas progressivas',
  'FALTAS SOFRIDAS': 'Faltas sofridas',
  'OFFSIDES': 'Offsides',
  'DUELOS TOTAIS': 'Duelos totais',
  'DUELOS GANHOS': 'Duelos ganhos',
  'DUELOS GANHOS, %': 'Duelos ganhos, %',
  'ACELERAÇÕES': 'Acelerações',
  'DISTÂNCIA PERCORRIDA': 'Distância percorrida',
  'SPRINTS': 'Sprints',
  'IDADE': 'Idade',
  'MINUTOS JOGADOS': 'Minutos jogados',
  'PARTIDAS JOGADAS': 'Partidas jogadas',
  'TITULARIDADES': 'Titularidades',
  'SUBSTITUIÇÕES': 'Substituições',
  'VALOR DE MERCADO': 'Valor de mercado',
  'CONTRATO ATÉ': 'Contrato até',
  'ID_ATLETA': 'ID_ATLETA'
};
