export const jogadores = [
  {
    "?": 22,
    "Jogador": "Alexis Ivan Alvarino",
    "Time": "Grêmio Novorizontino",
    "Idade": 24,
    "Altura": "184",
    "Peso": "81",
    "Nacionalidade": "Argentina",
    "Index": "186",
    "Posição": "RD"
  },
  {
    "?": 77,
    "Jogador": "Mayk",
    "Time": "Grêmio Novorizontino",
    "Idade": 26,
    "Altura": "172",
    "Peso": "67",
    "Nacionalidade": "Brazil",
    "Index": "193",
    "Posição": "LD"
  },
  {
    "?": 21,
    "Jogador": "Raul Prata",
    "Time": "Grêmio Novorizontino",
    "Idade": 37,
    "Altura": "175",
    "Peso": "72",
    "Nacionalidade": "Brazil",
    "Index": "186",
    "Posição": "RD"
  },
  {
    "?": 16,
    "Jogador": "Reverson",
    "Time": "Grêmio Novorizontino",
    "Idade": 27,
    "Altura": "180",
    "Peso": "75",
    "Nacionalidade": "Brazil",
    "Index": "190",
    "Posição": "LD"
  },
  {
    "?": 2,
    "Jogador": "Rodrigo Soares",
    "Time": "Grêmio Novorizontino",
    "Idade": 32,
    "Altura": "177",
    "Peso": "75",
    "Nacionalidade": "Brazil",
    "Index": "192",
    "Posição": "RD"
  },
  {
    "?": 31,
    "Jogador": "Danilo Barcelos",
    "Time": "Grêmio Novorizontino",
    "Idade": 33,
    "Altura": "186",
    "Peso": "79",
    "Nacionalidade": "Brazil",
    "Index": "184",
    "Posição": "LD"
  },
  {
    "?": 4,
    "Jogador": "Patrick",
    "Time": "Grêmio Novorizontino",
    "Idade": 26,
    "Altura": "188",
    "Peso": "82",
    "Nacionalidade": "Brazil",
    "Index": "208",
    "Posição": "ZG"
  },
  {
    "?": 3,
    "Jogador": "Rafael Donato",
    "Time": "Grêmio Novorizontino",
    "Idade": 35,
    "Altura": "194",
    "Peso": "95",
    "Nacionalidade": "Brazil",
    "Index": "204",
    "Posição": "ZG"
  },
  {
    "?": 28,
    "Jogador": "César Martins",
    "Time": "Grêmio Novorizontino",
    "Idade": 32,
    "Altura": "190",
    "Peso": "84",
    "Nacionalidade": "Brazil",
    "Index": "199",
    "Posição": "ZG"
  },
  {
    "?": 44,
    "Jogador": "Luisão",
    "Time": "Grêmio Novorizontino",
    "Idade": 26,
    "Altura": "188",
    "Peso": "80",
    "Nacionalidade": "Brazil",
    "Index": "195",
    "Posição": "ZG"
  },
  {
    "?": 33,
    "Jogador": "Renato Palm",
    "Time": "Grêmio Novorizontino",
    "Idade": 25,
    "Altura": "184",
    "Peso": "80",
    "Nacionalidade": "Brazil",
    "Index": "191",
    "Posição": "ZG"
  },
  {
    "?": 5,
    "Jogador": "Geovane",
    "Time": "Grêmio Novorizontino",
    "Idade": 26,
    "Altura": "179",
    "Peso": "76",
    "Nacionalidade": "Brazil",
    "Index": "198",
    "Posição": "VOL"
  },
  {
    "?": 15,
    "Jogador": "Dudu",
    "Time": "Grêmio Novorizontino",
    "Idade": 25,
    "Altura": "176",
    "Peso": "74",
    "Nacionalidade": "Brazil",
    "Index": "196",
    "Posição": "VOL"
  },
  {
    "?": 25,
    "Jogador": "Marlon",
    "Time": "Grêmio Novorizontino",
    "Idade": 34,
    "Altura": "178",
    "Peso": "75",
    "Nacionalidade": "Brazil",
    "Index": "194",
    "Posição": "VOL"
  },
  {
    "?": 8,
    "Jogador": "Willian Farias",
    "Time": "Grêmio Novorizontino",
    "Idade": 35,
    "Altura": "177",
    "Peso": "76",
    "Nacionalidade": "Brazil",
    "Index": "188",
    "Posição": "VOL"
  },
  {
    "?": 10,
    "Jogador": "Eduardo",
    "Time": "Grêmio Novorizontino",
    "Idade": 29,
    "Altura": "182",
    "Peso": "78",
    "Nacionalidade": "Brazil",
    "Index": "192",
    "Posição": "MC"
  },
  {
    "?": 7,
    "Jogador": "Rodolfo",
    "Time": "Grêmio Novorizontino",
    "Idade": 32,
    "Altura": "175",
    "Peso": "70",
    "Nacionalidade": "Brazil",
    "Index": "185",
    "Posição": "ATA"
  },
  {
    "?": 11,
    "Jogador": "Lucca",
    "Time": "Grêmio Novorizontino",
    "Idade": 21,
    "Altura": "180",
    "Peso": "75",
    "Nacionalidade": "Brazil",
    "Index": "182",
    "Posição": "ATA"
  },
  {
    "?": 9,
    "Jogador": "Neto Pessoa",
    "Time": "Grêmio Novorizontino",
    "Idade": 30,
    "Altura": "183",
    "Peso": "80",
    "Nacionalidade": "Brazil",
    "Index": "195",
    "Posição": "ATA"
  },
  {
    "?": 19,
    "Jogador": "Léo Tocantins",
    "Time": "Grêmio Novorizontino",
    "Idade": 26,
    "Altura": "178",
    "Peso": "74",
    "Nacionalidade": "Brazil",
    "Index": "188",
    "Posição": "ATA"
  },
  {
    "?": 99,
    "Jogador": "Waguininho",
    "Time": "Grêmio Novorizontino",
    "Idade": 34,
    "Altura": "178",
    "Peso": "74",
    "Nacionalidade": "Brazil",
    "Index": "186",
    "Posição": "ATA"
  },
  {
    "?": 1,
    "Jogador": "Jordi",
    "Time": "Grêmio Novorizontino",
    "Idade": 31,
    "Altura": "192",
    "Peso": "88",
    "Nacionalidade": "Brazil",
    "Index": "198",
    "Posição": "GOL"
  },
  {
    "?": 12,
    "Jogador": "Airton",
    "Time": "Grêmio Novorizontino",
    "Idade": 30,
    "Altura": "188",
    "Peso": "84",
    "Nacionalidade": "Brazil",
    "Index": "185",
    "Posição": "GOL"
  }
]
