export const elencoReal = [
  {
    "Numero": "22",
    "Jogador": "Alexis Ivan Alvarino",
    "Nacionalidade": "Argentina",
    "Altura": "184",
    "Idade": "24",
    "Posicao": "RD",
    "Index": "186",
    "Partidas": "3",
    "Gols": "-",
    "Acoes_Sucesso": "82%",
    "Passes_Precisos": "83%",
    "Dribles": "0,3",
    "Desafios": "56%",
    "Minutos": "296"
  },
  {
    "Numero": "77",
    "Jogador": "Mayk",
    "Nacionalidade": "Brazil",
    "Altura": "172",
    "Idade": "26",
    "Posicao": "LD",
    "Index": "193",
    "Partidas": "3",
    "Gols": "-",
    "Acoes_Sucesso": "87%",
    "Passes_Precisos": "86%",
    "Dribles": "2,13",
    "Desafios": "86%",
    "Minutos": "296"
  },
  {
    "Numero": "6",
    "Jogador": "Luis Felipe Oyama",
    "Nacionalidade": "Brazil",
    "Altura": "171",
    "Idade": "28",
    "Posicao": "RCDM",
    "Index": "164",
    "Partidas": "3",
    "Gols": "-",
    "Acoes_Sucesso": "79%",
    "Passes_Precisos": "85%",
    "Dribles": "1,25",
    "Desafios": "37%",
    "Minutos": "287"
  },
  {
    "Numero": "11",
    "Jogador": "Robson Fernandes",
    "Nacionalidade": "Brazil",
    "Altura": "179",
    "Idade": "34",
    "Posicao": "CF",
    "Index": "201",
    "Partidas": "3",
    "Gols": "0,97",
    "Acoes_Sucesso": "51%",
    "Passes_Precisos": "73%",
    "Dribles": "0,97",
    "Desafios": "25%",
    "Minutos": "279"
  },
  {
    "Numero": "18",
    "Jogador": "Léo Naldi",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "24",
    "Posicao": "LCDM",
    "Index": "164",
    "Partidas": "3",
    "Gols": "-",
    "Acoes_Sucesso": "78%",
    "Passes_Precisos": "88%",
    "Dribles": "1",
    "Desafios": "38%",
    "Minutos": "271"
  },
  {
    "Numero": "10",
    "Jogador": "Rômulo",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "24",
    "Posicao": "CAM",
    "Index": "190",
    "Partidas": "3",
    "Gols": "0,38",
    "Acoes_Sucesso": "64%",
    "Passes_Precisos": "71%",
    "Dribles": "0,38",
    "Desafios": "21%",
    "Minutos": "239"
  },
  {
    "Numero": "15",
    "Jogador": "Luiz Otavio Maria",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "21",
    "Posicao": "RAM",
    "Index": "192",
    "Partidas": "3",
    "Gols": "-",
    "Acoes_Sucesso": "73%",
    "Passes_Precisos": "83%",
    "Dribles": "3,03",
    "Desafios": "33%",
    "Minutos": "238"
  },
  {
    "Numero": "25",
    "Jogador": "Joao Vitor Silva Dantas de Oliveira",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "21",
    "Posicao": "CD",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "91%",
    "Passes_Precisos": "92%",
    "Dribles": "0,91",
    "Desafios": "83%",
    "Minutos": "198"
  },
  {
    "Numero": "19",
    "Jogador": "Diego Henrique Galo da Silva",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "20",
    "Posicao": "LAM",
    "Index": "184",
    "Partidas": "3",
    "Gols": "0,46",
    "Acoes_Sucesso": "69%",
    "Passes_Precisos": "70%",
    "Dribles": "1,39",
    "Desafios": "48%",
    "Minutos": "194"
  },
  {
    "Numero": "14",
    "Jogador": "Brock",
    "Nacionalidade": "Brazil, Italy",
    "Altura": "186",
    "Idade": "34",
    "Posicao": "LCD",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "86%",
    "Passes_Precisos": "88%",
    "Dribles": "-",
    "Desafios": "50%",
    "Minutos": "171"
  },
  {
    "Numero": "4",
    "Jogador": "Patrick Marcos de Sousa Freitas",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "26",
    "Posicao": "LCD",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "90%",
    "Passes_Precisos": "88%",
    "Dribles": "0,72",
    "Desafios": "77%",
    "Minutos": "125"
  },
  {
    "Numero": "26",
    "Jogador": "Gabriel Bahia",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "27",
    "Posicao": "RCD",
    "Index": "-",
    "Partidas": "1",
    "Gols": "-",
    "Acoes_Sucesso": "81%",
    "Passes_Precisos": "78%",
    "Dribles": "-",
    "Desafios": "63%",
    "Minutos": "98"
  },
  {
    "Numero": "50",
    "Jogador": "Juninho",
    "Nacionalidade": "Brazil",
    "Altura": "174",
    "Idade": "24",
    "Posicao": "LCM",
    "Index": "178",
    "Partidas": "3",
    "Gols": "1,41",
    "Acoes_Sucesso": "74%",
    "Passes_Precisos": "88%",
    "Dribles": "1,41",
    "Desafios": "25%",
    "Minutos": "64"
  },
  {
    "Numero": "41",
    "Jogador": "Helio",
    "Nacionalidade": "Brazil",
    "Altura": "174",
    "Idade": "25",
    "Posicao": "RDM",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "74%",
    "Passes_Precisos": "70%",
    "Dribles": "8,33",
    "Desafios": "64%",
    "Minutos": "54"
  },
  {
    "Numero": "66",
    "Jogador": "Maykon Jesus",
    "Nacionalidade": "Brazil",
    "Altura": "-",
    "Idade": "20",
    "Posicao": "LAM",
    "Index": "-",
    "Partidas": "1",
    "Gols": "1,8",
    "Acoes_Sucesso": "48%",
    "Passes_Precisos": "60%",
    "Dribles": "1,8",
    "Desafios": "30%",
    "Minutos": "50"
  },
  {
    "Numero": "30",
    "Jogador": "Nicolas Careca",
    "Nacionalidade": "Brazil",
    "Altura": "187",
    "Idade": "28",
    "Posicao": "CF",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "42%",
    "Passes_Precisos": "60%",
    "Dribles": "-",
    "Desafios": "22%",
    "Minutos": "30"
  },
  {
    "Numero": "7",
    "Jogador": "Airton Moises Santos Sousa",
    "Nacionalidade": "Brazil",
    "Altura": "178",
    "Idade": "26",
    "Posicao": "RAM",
    "Index": "-",
    "Partidas": "1",
    "Gols": "-",
    "Acoes_Sucesso": "60%",
    "Passes_Precisos": "63%",
    "Dribles": "-",
    "Desafios": "40%",
    "Minutos": "23"
  },
  {
    "Numero": "17",
    "Jogador": "Matheus Bianqui",
    "Nacionalidade": "Brazil",
    "Altura": "187",
    "Idade": "27",
    "Posicao": "RCM",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "64%",
    "Passes_Precisos": "100%",
    "Dribles": "-",
    "Desafios": "33%",
    "Minutos": "19"
  },
  {
    "Numero": "16",
    "Jogador": "Vinicius",
    "Nacionalidade": "Brazil",
    "Altura": "170",
    "Idade": "24",
    "Posicao": "LCAM",
    "Index": "-",
    "Partidas": "2",
    "Gols": "-",
    "Acoes_Sucesso": "82%",
    "Passes_Precisos": "75%",
    "Dribles": "5,62",
    "Desafios": "67%",
    "Minutos": "16"
  },
  {
    "Numero": "5",
    "Jogador": "Jean Carlos De Souza Irmer",
    "Nacionalidade": "Brazil",
    "Altura": "183",
    "Idade": "31",
    "Posicao": "LCDM",
    "Index": "-",
    "Partidas": "1",
    "Gols": "-",
    "Acoes_Sucesso": "83%",
    "Passes_Precisos": "75%",
    "Dribles": "-",
    "Desafios": "-",
    "Minutos": "4"
  }
];