export const elencoReal = [
  {
    "Numero": "11",
    "Jogador": "Robson",
    "Nacionalidade": "BRA",
    "Altura": "179",
    "Idade": "34",
    "Posicao_Original": "",
    "Gols": "0,97",
    "Partidas": 3,
    "Minutos": 279,
    "Acoes_Sucesso": "51%",
    "Passes_Precisos": "73%",
    "Dribles": "0,97",
    "Desafios": "25%",
    "Posicao": "CF",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "40",
    "Jogador": "Jardiel",
    "Nacionalidade": "BRA",
    "Altura": "182",
    "Idade": "20",
    "Posicao_Original": "",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "90",
    "Jogador": "Caio Dantas",
    "Nacionalidade": "BRA",
    "Altura": "177",
    "Idade": "32",
    "Posicao_Original": "",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "7",
    "Jogador": "Airton",
    "Nacionalidade": "BRA",
    "Altura": "178",
    "Idade": "26",
    "Posicao_Original": "",
    "Gols": "-",
    "Partidas": 1,
    "Minutos": 23,
    "Acoes_Sucesso": "60%",
    "Passes_Precisos": "63%",
    "Dribles": "-",
    "Desafios": "40%",
    "Posicao": "RAM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "30",
    "Jogador": "Nicolas Careca",
    "Nacionalidade": "BRA",
    "Altura": "188",
    "Idade": "28",
    "Posicao_Original": "",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 30,
    "Acoes_Sucesso": "42%",
    "Passes_Precisos": "60%",
    "Dribles": "-",
    "Desafios": "22%",
    "Posicao": "CF",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "10",
    "Jogador": "Rômulo",
    "Nacionalidade": "BRA",
    "Altura": "176",
    "Idade": "24",
    "Posicao_Original": "MEI",
    "Gols": "0,38",
    "Partidas": 3,
    "Minutos": 239,
    "Acoes_Sucesso": "64%",
    "Passes_Precisos": "71%",
    "Dribles": "0,38",
    "Desafios": "21%",
    "Posicao": "CAM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "6",
    "Jogador": "Luís Oyama",
    "Nacionalidade": "BRA",
    "Altura": "171",
    "Idade": "29",
    "Posicao_Original": "MEI",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "MEI",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "18",
    "Jogador": "Leo Naldi",
    "Nacionalidade": "BRA",
    "Altura": "177",
    "Idade": "24",
    "Posicao_Original": "MEI",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "MEI",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "66",
    "Jogador": "Maykon Jesus",
    "Nacionalidade": "BRA",
    "Altura": "181",
    "Idade": "20",
    "Posicao_Original": "MEI",
    "Gols": "1,8",
    "Partidas": 1,
    "Minutos": 50,
    "Acoes_Sucesso": "48%",
    "Passes_Precisos": "60%",
    "Dribles": "1,8",
    "Desafios": "30%",
    "Posicao": "LAM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "16",
    "Jogador": "Vinicius Paiva",
    "Nacionalidade": "BRA",
    "Altura": "170",
    "Idade": "24",
    "Posicao_Original": "MEI",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 16,
    "Acoes_Sucesso": "82%",
    "Passes_Precisos": "75%",
    "Dribles": "5,62",
    "Desafios": "67%",
    "Posicao": "LCAM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "50",
    "Jogador": "Juninho",
    "Nacionalidade": "BRA",
    "Altura": "174",
    "Idade": "25",
    "Posicao_Original": "MEI",
    "Gols": "1,41",
    "Partidas": 3,
    "Minutos": 64,
    "Acoes_Sucesso": "74%",
    "Passes_Precisos": "88%",
    "Dribles": "1,41",
    "Desafios": "25%",
    "Posicao": "LCM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "17",
    "Jogador": "Matheus Bianqui",
    "Nacionalidade": "BRA",
    "Altura": "187",
    "Idade": "28",
    "Posicao_Original": "MEI",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 19,
    "Acoes_Sucesso": "64%",
    "Passes_Precisos": "100%",
    "Dribles": "-",
    "Desafios": "33%",
    "Posicao": "RCM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "41",
    "Jogador": "Hélio Borges",
    "Nacionalidade": "BRA",
    "Altura": "175",
    "Idade": "25",
    "Posicao_Original": "MEI",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "MEI",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "28",
    "Jogador": "Marlon",
    "Nacionalidade": "BRA",
    "Altura": "175",
    "Idade": "35",
    "Posicao_Original": "MEI",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 198,
    "Acoes_Sucesso": "89%",
    "Passes_Precisos": "92%",
    "Dribles": "-",
    "Desafios": "50%",
    "Posicao": "LCDM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "23",
    "Jogador": "Luiz GabrielMidfielder",
    "Nacionalidade": "BRA",
    "Altura": "-",
    "Idade": "21",
    "Posicao_Original": "MEI",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 145,
    "Acoes_Sucesso": "64%",
    "Passes_Precisos": "74%",
    "Dribles": "-",
    "Desafios": "35%",
    "Posicao": "LCM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "77",
    "Jogador": "Mayk Silva",
    "Nacionalidade": "BRA",
    "Altura": "172",
    "Idade": "26",
    "Posicao_Original": "DEF",
    "Gols": "-",
    "Partidas": 3,
    "Minutos": 296,
    "Acoes_Sucesso": "87%",
    "Passes_Precisos": "86%",
    "Dribles": "2,13",
    "Desafios": "86%",
    "Posicao": "LD",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "24",
    "Jogador": "Jhilmar Lora",
    "Nacionalidade": "PER",
    "Altura": "176",
    "Idade": "25",
    "Posicao_Original": "DEF",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "DEF",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "26",
    "Jogador": "Gabriel Bahia",
    "Nacionalidade": "BRA",
    "Altura": "188",
    "Idade": "27",
    "Posicao_Original": "DEF",
    "Gols": "-",
    "Partidas": 1,
    "Minutos": 98,
    "Acoes_Sucesso": "81%",
    "Passes_Precisos": "78%",
    "Dribles": "-",
    "Desafios": "63%",
    "Posicao": "RCD",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "25",
    "Jogador": "Dantas",
    "Nacionalidade": "BRA",
    "Altura": "189",
    "Idade": "21",
    "Posicao_Original": "DEF",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 198,
    "Acoes_Sucesso": "91%",
    "Passes_Precisos": "92%",
    "Dribles": "0,91",
    "Desafios": "83%",
    "Posicao": "CD",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "4",
    "Jogador": "Patrick",
    "Nacionalidade": "BRA",
    "Altura": "183",
    "Idade": "26",
    "Posicao_Original": "DEF",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 125,
    "Acoes_Sucesso": "90%",
    "Passes_Precisos": "88%",
    "Dribles": "0,72",
    "Desafios": "77%",
    "Posicao": "LCD",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "14",
    "Jogador": "Eduardo Brock",
    "Nacionalidade": "BRA",
    "Altura": "186",
    "Idade": "34",
    "Posicao_Original": "DEF",
    "Gols": "-",
    "Partidas": 2,
    "Minutos": 171,
    "Acoes_Sucesso": "86%",
    "Passes_Precisos": "88%",
    "Dribles": "-",
    "Desafios": "50%",
    "Posicao": "LCD",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "22",
    "Jogador": "Alexis Alvarino",
    "Nacionalidade": "ARG",
    "Altura": "184",
    "Idade": "24",
    "Posicao_Original": "DEF",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "DEF",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "-",
    "Jogador": "Nilson Castrillón",
    "Nacionalidade": "COL",
    "Altura": "181",
    "Idade": "30",
    "Posicao_Original": "DEF",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "DEF",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "33",
    "Jogador": "Renato Silveira",
    "Nacionalidade": "BRA",
    "Altura": "188",
    "Idade": "34",
    "Posicao_Original": "DEF",
    "Gols": "1,27",
    "Partidas": 2,
    "Minutos": 71,
    "Acoes_Sucesso": "68%",
    "Passes_Precisos": "79%",
    "Dribles": "-",
    "Desafios": "46%",
    "Posicao": "CAM",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "21",
    "Jogador": "AlemãoDefender",
    "Nacionalidade": "BRA",
    "Altura": "186",
    "Idade": "18",
    "Posicao_Original": "DEF",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "DEF",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "31",
    "Jogador": "César",
    "Nacionalidade": "BRA",
    "Altura": "191",
    "Idade": "30",
    "Posicao_Original": "GOL",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "GOL",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "93",
    "Jogador": "Jordi",
    "Nacionalidade": "BRA",
    "Altura": "191",
    "Idade": "32",
    "Posicao_Original": "GOL",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "GOL",
    "Nota_Media": "7.1"
  },
  {
    "Numero": "1",
    "Jogador": "Lucas Pereira",
    "Nacionalidade": "BRA",
    "Altura": "191",
    "Idade": "27",
    "Posicao_Original": "GOL",
    "Gols": "0",
    "Partidas": "0",
    "Minutos": "0",
    "Acoes_Sucesso": "0%",
    "Passes_Precisos": "0%",
    "Dribles": "0",
    "Desafios": "0%",
    "Posicao": "GOL",
    "Nota_Media": "7.1"
  }
];